# Generated by Django 3.0.7 on 2021-06-01 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20210601_1301'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
